FizzBuzzWeb/Models/FizzBuzzModel.cs
namespace FizzBuzzWeb.Models
{
    using System.ComponentModel.DataAnnotations;
    using PagedList.Mvc;
    using PagedList;

    public class FizzBuzzModel
    {
        public IPagedList<string> FizzBuzzNumbers { get; set; }

        [Range(1, 1000, ErrorMessage = "The Number Should be Between 1 to 1000")]
        [Required]
        public int Input { get; set; }
    }
}

FizzBuzzWeb/Controllers/FizzBuzzController.cs
namespace FizzBuzzWeb.Controllers
{
    using System.Web.Mvc;
    using FizzBuzzWeb.Models;
    using FizzBuzz.Services.Interfaces;
    using PagedList;

    public class FizzBuzzController : Controller
    {
        private const int PageSize = 20;
        private readonly IFizzBuzzService fizzBuzz;

        public FizzBuzzController(IFizzBuzzService fizzBuzz)
        {
            this.fizzBuzz = fizzBuzz;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return this.View(new FizzBuzzModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(FizzBuzzModel model)
        {
            return this.GetView(1, model);
        }

        public ActionResult Navigate(int input, int page)
        {
            var model = new FizzBuzzModel { Input = input };
            return GetView(page, model);
        }

        private ActionResult GetView(int page, FizzBuzzModel model)
        {
            if (this.ModelState.IsValid)
            {
                model.FizzBuzzNumbers = this.fizzBuzz.GetResult(model.Input).ToPagedList(page, PageSize);
            }
            return this.View("Index", model);
        }
    }
}

FizzBuzzWeb/Views/FizzBuzz/Index.cshtml
@using PagedList.Mvc
@model FizzBuzzWeb.Models.FizzBuzzModel

@using (Html.BeginForm("Index", "FizzBuzz", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="form-group">
        @Html.LabelFor(a => a.Input, "Enter The Integer : ")
        @Html.TextBoxFor(m => m.Input, new { @id = "Input", placeholder = "Enter Integer Number", Value = "" })
        @Html.ValidationMessageFor(m => m.Input)
    </div>
    <div class="form-group">
        <input type="submit" value="Submit" class="btn-default" />
    </div>
    <div>
        @if (Model.FizzBuzzNumbers != null)
        {
            foreach (var val in Model.FizzBuzzNumbers)
            {
                <div class="@val">@val</div>
            }
            <div>
                Page @(Model.FizzBuzzNumbers.PageCount < Model.FizzBuzzNumbers.PageNumber ? 0 : Model.FizzBuzzNumbers.PageNumber) of @Model.FizzBuzzNumbers.PageCount
                @Html.PagedListPager(Model.FizzBuzzNumbers, page => Url.Action("Navigate", "FizzBuzz", new { Model.Input, page }))
            </div>
        }
    </div>
}

FizzBuzzWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/FizzBuzz.css" rel="stylesheet">
</head>
<body>
    <h3>Fizz-Buzz Numbers</h3>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap") 
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>